/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, Text, View, Button} from 'react-native';
import TTSEdge, {
  createTextToSpeechBySSML,
  createTextToSpeechByText,
  stopEdge,
} from 'react-native-text-to-speech-edge';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
  };
  componentDidMount() {
    console.log("TTSEdge", TTSEdge)
    
    TTSEdge.addEventListener('ttedge-finish', (event) =>
      console.log('ttedge-finish', event) // Your Listener To Finish Audio
    );
  }

  playText = () => {
    
    createTextToSpeechByText(
      'Olá Matheus, você é Corinthiano?',
      'pt-BR-FranciscaNeural',
      'Your Key in Here',
      'Your Region in Here',
    )
      .then((isFinal) => {
        console.log('Success');
      })
      .catch((error) => {
        console.log('Error', error);
      });
  };

  playTextSSML = () => {

    const ssmlText =
      '<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="pt-BR"><voice name="pt-BR-FranciscaNeural"><mstts:express-as style="Cheerful">Lewis Hamilton conquistou neste domingo uma dramática vitória no GP da Inglaterra após ter o pneu dianteiro esquerdo furado na última volta. Mesmo se arrastando nas últimas curvas.</mstts:express-as></voice></speak>';

    createTextToSpeechBySSML(
      ssmlText,
      '',
      'Your Key in Here',
      'Your Region in Here',
    )
      .then((isFinal) => {
        console.log('Success');
      })
      .catch((error) => {
        console.log('Error', error);
      });
  };

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆TextToSpeechEdge example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Button title="Play in Text" onPress={this.playText} />
        <Button title="Play in Text - SSML" onPress={this.playTextSSML} />
        <Button title="Stop Audio" onPress={() => {
          stopEdge()
        }} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
